site_name: Settlers United Documentation
site_url: http://127.0.0.1:8000/

extra_css:
  - ../stylesheets/extra.css

plugins:
  - search
  - awesome-pages

markdown_extensions:
  - attr_list
  - abbr
  - md_in_html
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

theme:
  features:
    - navigation.tracking
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - content.tooltips
    - announce.dismiss
    - search.suggest
    - search.highlight
  custom_dir: '../../assets/'
  name: material
  palette:
    scheme: slate
    primary: black
    accent: deep orange
extra:
  alternate:
    - name: English
      link: /en/ 
      lang: en
    - name: Deutsch
      link: /de/
      lang: de


